TELEGRAM_TOKEN = 'YOUR_TELEGRAM_BOT_TOKEN_HERE'
GEMINI_API_KEY = 'YOUR_GEMINI_API_KEY_HERE'
YOUR_CHAT_ID = 'YOUR_TELEGRAM_CHAT_ID_HERE'

SPEECH_SA_KEY_PATH = "speech-sa-key.json"
GOOGLE_CREDENTIALS_PATH = "credentials.json"

NEWS_SOURCE_HOMEpages = [
    "https://www.aljazeera.com/news/", 
]
